# Use the official Nginx image
FROM nginx:alpine

# Copy the index.html to the appropriate directory in the container
COPY index.html /usr/share/nginx/html/index.html

# Expose port 80 to access the web page
EXPOSE 80
