apiVersion: v1
kind: Service
metadata:
  name: nginx-service1
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80  # Exposing port 80 externally
      targetPort: 80  # Port inside the container
  type: NodePort  # Use NodePort for local access
