apiVersion: v1
kind: Service
metadata:
  name: nginx-service2
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80  # Exposing port 80
      targetPort: 80  # Inside the container
  type: NodePort    # Or you can use NodePort if LoadBalancer isn't available
