# docker-compose.yml
version: '3.8'

services:
  apache-server:
    build: ./apache-server
    container_name: apache-server
    ports:
      - "8085:80"
    networks:
      - app-network

  ansible:
    build: ./ansible
    container_name: ansible-container
    depends_on:
      - apache-server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge